development:
  adapter: postgresql
  database: development
  host: localhost

test:
  adapter: postgresql
  database: test
  username: postgres
  password: ENV['POSTGRES_PASSWORD']
  host: localhost

production:
  adapter: postgresql
  database: hollaback
  username: hollaback
  password: ENV['POSTGRES_PASSWORD']
  host: localhost